const fs=require('fs');const ler=p=>fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'');const gravar=(p,t)=>fs.writeFileSync(p,t,'utf8');
let original=ler('Dados/refatoracao/Controllers_EquipamentosController.cs');
let foto=original.slice(original.indexOf('        var extensao ='),original.indexOf('    [HttpGet("{id:int}/termo")]'));
foto=foto.replace('arquivo.FileName','nomeArquivo').split('arquivo.Length').join('tamanho').replace('arquivo.CopyToAsync(memoria)','conteudo.CopyToAsync(memoria)').replace('await AlterarFotoAsync(id, nome)','await AlterarFotoAsync(id, nome, usuario)').replace('return Ok(new { foto = nome });','return nome;').replace('    [HttpDelete("{id:int}/foto")]\n','').replace('public async Task<IActionResult> RemoverFoto(int id) { await AlterarFotoAsync(id, null); return NoContent(); }','public Task RemoverAsync(int id, int usuario) => AlterarFotoAsync(id, null, usuario);').replace('private async Task AlterarFotoAsync(int id, string? nome)','private async Task AlterarFotoAsync(int id, string? nome, int usuario)').replace('await conexao.QuerySingleOrDefaultAsync<Equipamento>("SELECT * FROM equipamentos WHERE Id=@id FOR UPDATE", new { id }, transacao)','await repositorio.ObterParaAtualizacaoAsync(conexao, new { id }, transacao)').replace('await conexao.ExecuteAsync("UPDATE equipamentos SET Foto=@nome,AtualizadoEm=CURRENT_TIMESTAMP WHERE Id=@id", new { nome, id }, transacao)','await repositorio.AtualizarFotoAsync(conexao, id, nome, transacao)').replace('ServicoEquipamentos.RegistrarHistoricoAsync(conexao, transacao, id, UsuarioAtual','servicoEquipamentos.RegistrarHistoricoAsync(conexao, transacao, id, usuario').replace('    [HttpGet("{id:int}/foto")]\n','').replace('Task<IActionResult> Foto(int id)','Task<FotoDisponivel?> ObterAsync(int id)').replace('await conexao.ExecuteScalarAsync<string>("SELECT Foto FROM equipamentos WHERE Id=@id", new { id })','await repositorio.ObterFotoAsync(conexao, id)').split('return NotFound();').join('return null;').replace('return PhysicalFile(caminho,','return new FotoDisponivel(caminho,');
gravar('Servicos/ServicoFotos.cs',`using JcaInventario.DTOs;\nusing JcaInventario.Infraestrutura;\nusing JcaInventario.Repositorios;\n\nnamespace JcaInventario.Servicos;\n\npublic class ServicoFotos(Banco banco, RepositorioEquipamentos repositorio, ServicoEquipamentos servicoEquipamentos, IWebHostEnvironment ambiente)\n{\n    public async Task<string> SalvarAsync(int id, string nomeArquivo, long tamanho, Stream conteudo, int usuario)\n    {\n${foto}}\n`);
let termo=original.slice(original.indexOf('        await using var conexao',original.indexOf('public async Task<IActionResult> Termo')),original.lastIndexOf('\n}'));
termo=termo.replace('await conexao.QuerySingleOrDefaultAsync(RepositorioInventario.ConsultaEquipamentos + " WHERE e.Id=@id", new { id })','await repositorio.ObterDetalhesAsync(conexao, id)').replace('return File(GeradorTermo.Gerar(linhas),','return new ArquivoGerado(GeradorTermo.Gerar(linhas),');
gravar('Servicos/ServicoTermos.cs',`using JcaInventario.DTOs;\nusing JcaInventario.Infraestrutura;\nusing JcaInventario.Repositorios;\n\nnamespace JcaInventario.Servicos;\n\npublic class ServicoTermos(Banco banco, RepositorioEquipamentos repositorio)\n{\n    public async Task<ArquivoGerado> GerarAsync(int id)\n    {\n${termo}\n}\n`);
// Separa o fluxo de manutenção do serviço de equipamentos.
let equipamentos=ler('Servicos/ServicoEquipamentos.cs');
let manutencao=equipamentos.slice(equipamentos.indexOf('    public async Task<int> SalvarManutencaoAsync'),equipamentos.lastIndexOf('\n}'));
equipamentos=equipamentos.slice(0,equipamentos.indexOf('    public async Task<int> SalvarManutencaoAsync'))+'}\n';
manutencao=manutencao.replace('SalvarManutencaoAsync','SalvarAsync').split('await RegistrarMovimentacaoAsync').join('await servicoEquipamentos.RegistrarMovimentacaoAsync').split('await RegistrarHistoricoAsync').join('await servicoEquipamentos.RegistrarHistoricoAsync');
gravar('Servicos/ServicoManutencoes.cs',`using JcaInventario.Infraestrutura;\nusing JcaInventario.Modelos;\nusing JcaInventario.Repositorios;\nusing System.Text.Json;\n\nnamespace JcaInventario.Servicos;\n\npublic class ServicoManutencoes(Banco banco, RepositorioEquipamentos repositorio, ServicoEquipamentos servicoEquipamentos)\n{\n${manutencao}\n}\n`);
const consultas=`    public async Task<object> ListarAsync()\n    {\n        await using var conexao = await banco.AbrirAsync();\n        return await repositorio.ListarAsync(conexao);\n    }\n\n    public async Task<object> ObterDetalhesAsync(int id)\n    {\n        await using var conexao = await banco.AbrirAsync();\n        var equipamento = await repositorio.ObterDetalhesAsync(conexao, id) ?? throw new KeyNotFoundException();\n        var movimentacoes = await repositorio.ListarMovimentacoesAsync(conexao, id);\n        var manutencoes = await repositorio.ListarManutencoesAsync(conexao, id);\n        var historico = await repositorio.ListarHistoricoAsync(conexao, id);\n        return new { equipamento, movimentacoes, manutencoes, historico };\n    }\n`;
equipamentos=equipamentos.slice(0,equipamentos.lastIndexOf('}'))+consultas+'}\n';gravar('Servicos/ServicoEquipamentos.cs',equipamentos);
